import { viteBundler } from '@vuepress/bundler-vite'
import { defaultTheme } from '@vuepress/theme-default'
import { defineUserConfig } from 'vuepress'

export default defineUserConfig({
  lang: 'en-US',
  title: 'Whispr Backend Documentation 🎉',
  description: 'Modern real-time messaging API built with NestJS, TypeScript, and PostgreSQL',
  base: process.env.DEPLOY_ENV === 'gh-pages' ? '/awesome-nest-boilerplate/' : '/',
  bundler: viteBundler({
    viteOptions: {},
    vuePluginOptions: {},
  }),
  theme: defaultTheme({
    colorMode: 'light',
    sidebar: [
      // ['/', 'Introduction'],
      // '/docs/development',
      // '/docs/architecture',
      // '/docs/naming-cheatsheet',
      // '/docs/linting',
      // '/docs/troubleshooting',
      // Generated by Copilot
        {
          text: 'Guide',
          children: [
            '/',
            '/docs/development',
            '/docs/architecture',
            '/docs/naming-cheatsheet',
            '/docs/linting',
            '/docs/code-generation',
          ],
        },
    ],
  }),
})
